#!/bin/bash
# Chaos Test: Master Orchestrator
# S11-CHAOS-01: Run all chaos scenarios and generate summary report
#
# Usage: ./run-all-chaos.sh
# Exit: 0 if ALL PASS, 1 if ANY FAIL

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RESULTS_DIR="${SCRIPT_DIR}/results"
REPORT_FILE="${SCRIPT_DIR}/results/chaos-summary.md"

mkdir -p "$RESULTS_DIR"

log() { echo "[$(date +%H:%M:%S)] $*"; }

log "╔══════════════════════════════════════════════╗"
log "║    UIP Chaos Engineering — Full Suite        ║"
log "║    S11-CHAOS-01                              ║"
log "╚══════════════════════════════════════════════╝"
echo ""

# Report header
cat > "$REPORT_FILE" <<EOF
# Chaos Engineering Test Report

**Date:** $(date +%Y-%m-%d)
**Time:** $(date +%H:%M:%S)
**Host:** $(hostname)
**Sprint:** 11 (S11-CHAOS-01)

---

## Test Scenarios

EOF

TOTAL=0
PASSED=0
FAILED=0

run_test() {
    local test_name="$1"
    local test_script="$2"

    TOTAL=$((TOTAL + 1))
    log "▶ Running: ${test_name}..."

    echo "### ${TOTAL}. ${test_name}" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    if bash "${SCRIPT_DIR}/${test_script}" 2>&1 | tee -a "${RESULTS_DIR}/${test_name}.log"; then
        PASSED=$((PASSED + 1))
        log "  ✅ ${test_name}: PASS"
        echo "**Result: ✅ PASS**" >> "$REPORT_FILE"
    else
        FAILED=$((FAILED + 1))
        log "  ❌ ${test_name}: FAIL"
        echo "**Result: ❌ FAIL**" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "See log: \`${RESULTS_DIR}/${test_name}.log\`" >> "$REPORT_FILE"
    fi

    echo "" >> "$REPORT_FILE"
    echo "---" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    # Cool-down between tests
    sleep 10
}

# ── Run all scenarios ───────────────────────────────────────────
run_test "Kafka Broker Failure" "chaos-kafka-broker.sh"
run_test "ClickHouse Node Failure" "chaos-clickhouse-node.sh"
run_test "Flink JobManager Crash" "chaos-flink-jobmanager.sh"
run_test "Network Partition" "chaos-network-partition.sh"

# ── Summary ─────────────────────────────────────────────────────
cat >> "$REPORT_FILE" <<EOF
## Summary

| Scenario | Result |
|----------|--------|
| Kafka Broker Failure | $(if grep -q "PASS" "${RESULTS_DIR}/Kafka Broker Failure-result.txt" 2>/dev/null; then echo "✅ PASS"; else echo "❌ FAIL"; fi) |
| ClickHouse Node Failure | $(if grep -q "PASS" "${RESULTS_DIR}/ClickHouse Node Failure-result.txt" 2>/dev/null; then echo "✅ PASS"; else echo "❌ FAIL"; fi) |
| Flink JobManager Crash | $(if grep -q "PASS" "${RESULTS_DIR}/Flink JobManager Crash-result.txt" 2>/dev/null; then echo "✅ PASS"; else echo "❌ FAIL"; fi) |
| Network Partition | $(if grep -q "PASS" "${RESULTS_DIR}/Network Partition-result.txt" 2>/dev/null; then echo "✅ PASS"; else echo "❌ FAIL"; fi) |

**Total:** ${TOTAL} | **Passed:** ${PASSED} | **Failed:** ${FAILED}

**Overall: $(if [[ $FAILED -eq 0 ]]; then echo "✅ ALL PASS"; else echo "❌ ${FAILED} FAILED"; fi)**

---

*Report generated by run-all-chaos.sh | S11-CHAOS-01*
EOF

echo ""
log "╔══════════════════════════════════════════════╗"
log "║  Results: ${PASSED}/${TOTAL} PASSED, ${FAILED} FAILED          ║"
log "╚══════════════════════════════════════════════╝"
log "Report: ${REPORT_FILE}"

if [[ $FAILED -gt 0 ]]; then
    exit 1
else
    exit 0
fi
